version: '3'

services:
  webapp:
    environment:
      - RAILS_ENV=development
      - PASSENGER_APP_ENV=development
    build:
      context: .
      cache_from:
        - docker.pkg.github.com/smarquezs/app/app-web
    image: app-web
    working_dir: /home/app/webapp
    ports:
      - '80'
    volumes:
      - .:/home/app/webapp
