on:
  push:
    branches:
      - master

name: Build docker image
jobs:
  build_image:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image
      run: docker build . -t test
