on:
  push:
    branches:
      - master

name: Build docker image
jobs:
  build_image_with_no_cache:
    name: Build with no cache
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image
      run: docker build . -t test

  build_image_with_cache:
    name: Build with cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - name: Build the docker image
        run: docker build . --tag test-cache
